# Generated by Django 3.1.4 on 2020-12-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mta', '0002_auto_20201226_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='favicon',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
