# Generated by Django 3.1.4 on 2020-12-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mta', '0003_home_favicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='hero_grey',
        ),
        migrations.AddField(
            model_name='home',
            name='hero_grey_l1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='home',
            name='hero_grey_l2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='home',
            name='hero_grey_l3',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='home',
            name='hero_grey_l4',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='home',
            name='hero_grey_l5',
            field=models.CharField(default='', max_length=500),
        ),
    ]
