# Generated by Django 3.1.4 on 2020-12-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mta', '0004_auto_20201226_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='address_l1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='home',
            name='address_l2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='home',
            name='address_l3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='home',
            name='address_l4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='home',
            name='address_l5',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='home',
            name='phone_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
