# Generated by Django 3.1.4 on 2020-12-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mta', '0007_auto_20201226_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email_id', models.CharField(default='', max_length=200)),
                ('phone_number', models.CharField(default='', max_length=13)),
                ('message', models.TextField()),
            ],
        ),
    ]
