# Generated by Django 3.1.5 on 2021-02-21 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mta', '0010_tour_packages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='img_big',
        ),
        migrations.RemoveField(
            model_name='data',
            name='img_big_text',
        ),
        migrations.RemoveField(
            model_name='data',
            name='img_small1',
        ),
        migrations.RemoveField(
            model_name='data',
            name='img_small1_text',
        ),
        migrations.RemoveField(
            model_name='data',
            name='img_small2',
        ),
        migrations.RemoveField(
            model_name='data',
            name='img_small2_text',
        ),
        migrations.RemoveField(
            model_name='data',
            name='img_small3',
        ),
        migrations.RemoveField(
            model_name='data',
            name='img_small3_text',
        ),
        migrations.RemoveField(
            model_name='data',
            name='img_small4',
        ),
        migrations.RemoveField(
            model_name='data',
            name='img_small4_text',
        ),
    ]
